site_name: DCOM Compliance Ecosystem Documentation
theme: windmill
markdown_extensions:
  - attr_list
extra:
  logo: dcom.png
nav:
  - Home: index.md
  - Compliance Ecosystem Architecture: architecture.md
  - Compliance Document Format: compliancedocument.md
  - Compliance Ecosystem APIs: ecosystemapi.md
  - Compliance Document Ecosystem Pilot Deployment Information: pilot.md
  - Compliance Ecosystem Core Java Library: core.md
